regions:
- "eu-west-1"

account-blacklist:
- "999999999999"

resource-types:
  targets:
  - EC2Instance
  - EC2Image
  - EC2Subnet
  - EC2InternetGateway
  - EC2NATGateway
  - EC2VPC
  - EC2DHCPOption
  - EC2RouteTable
  - ELB
  - ELBv2
  - ELBv2TargetGroup
  - EC2Volume
  - EC2SecurityGroup
  excludes:
  - S3Bucket
  - S3Object
  
accounts:
  "439428458691":
    filters:
      EC2Instance:
      - property: tag:Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2Image:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2Subnet:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2InternetGateway:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2NATGateway:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2VPC:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2DHCPOption:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2RouteTable:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      ELB:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      ELBv2:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      ELBv2TargetGroup:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2Volume:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true
      EC2SecurityGroup:
      - property: Name
        type: glob
        value: "{{app_env}}*"
        # invert: true